### ISSUE TITLE
for csv_dd, what is the "dataType" for date time? 

### ISSUE THREAD

**Issue by regnans** [ess-dive-community/essdive-uas#12]
Emily, is there a standard term here? dateTime, date-time, datetime??? Does it matter?

**Comment by emilyarobles** [comment]
@regnans "datetime" Data_Type should be used to distinguish datetime fields from date. It's not currently required, but we are planning to revise the CSV dd to include the recommendation.

**Comment by regnans** [comment]
thanks. I'll add that in
