### ISSUE TITLE
1_CampaignSummary: Contact

### ISSUE THREAD

**Issue by emilyarobles** [ess-dive-community/essdive-uas#14]
@regnans 
Could you clarify which individual should be listed as the contact? Is this the person who is filling out the dataset and submitting it, or the PI of the project, etc? 

The location reporting format also has a contact field (Submission_Contact_Name) and who exactly should be listed has caused some confusion in the past. Also, the location RF separates the contact name from the contact email. I would suggest something similar in this case, since First and Last name, Organization, Email, and ORCID could make this field quite lengthy. Additionally, it is unclear whether all of this information is required? Or just name and email? You could have a Name; Email field and an optional/recommended Organization; ORCID?

**Comment by regnans** [comment]
The Contact field here is the same as the ESS-DIVE package metadata. It is included in Campaign Summary to make the reporting format usable outside of ESS-DIVE, but within ESS-DIVE I expect that the Contact information will be taken from the Package Metadata, not the UAS metadata.
