### ISSUE TITLE
1_CampaignSummary: Pilot

### ISSUE THREAD

**Issue by emilyarobles** [ess-dive-community/essdive-uas#15]
Similarly to the contact information, I recommend separating pilot first/last name from organization, email, and license. However, since this is a recommended field and not a required one like the contact it's a bit less important.

**Comment by regnans** [comment]
Early in the development of this format Deb and Charu put a lot of emphasis on keeping things as simple and minimal as possible to give people the best chance of actually following any of the guidance. Keeping this in mind, I am hesitant to add additional rows to these metadata tables.

**Comment by emilyarobles** [comment]
Sounds good - since all contact information is remaining in a single field as well, it seems intuitive that this would follow the same format.
