### ISSUE TITLE
3_FlightDetails: DateTime_Start, DateTime_End

### ISSUE THREAD

**Issue by emilyarobles** [ess-dive-community/essdive-uas#17]
@regnans 
Is this variable required to be in UTC? If not, should contributors include offset in this field or separately?

**Comment by regnans** [comment]
UTC or local time are both acceptable. UTC offset can be included in the field, as per ISO timedate format (or not, up to the user). Also UTC offset should be specified in the FLMD file.

**Comment by regnans** [comment]
@emilyarobles are the variable names used for various DateTime variables consistent with the "ESS-DIVE standard" (or at least not conflicting too much if there is no standard yet)? Once that is good I think it's ready to publish as v1, if you agree.

**Comment by emilyarobles** [comment]
@regnans 
We've decided that it would be best to change the variable names to match the convention that the reporting formats will be transitioning to before releasing v1, to avoid having to revise so soon after releasing. After review, the data types, field formats, etc. all look good to me and I have no other suggestions for changes on your end. Unless you have anything else you'd like to address or any concerns about delaying release, I will move forward with starting the variable name revisions.

**Comment by regnans** [comment]
OK, I'm happy for you to do that. Each variable name will have to be revised in the metadata guides, the templates (there are 4 different versions of the sensor details template) and the dd file.
