### ISSUE TITLE
3_FlightDetails: flightHeight

### ISSUE THREAD

**Issue by emilyarobles** [ess-dive-community/essdive-uas#19]
**Just a suggestion**
To make the "Data_Type" in the data dictionary easier for this variable, you could separate this into two fields, both numeric, one _flight_height_agl_ and another _flight_height_amsl_ (or similar) and have the data contributor include whichever is relevant. The inclusion of "AGL" or "AMSL" in the same field as the numeric value will turn this into a string.

**Comment by regnans** [comment]
The data type should be text. (Or string, but I have been using text). I have updated the dd (to be uploaded later after working through other changes).
