### ISSUE TITLE
Reference CSV RF: UAS Data data product types and processing levels

### ISSUE THREAD

**Issue by emilyarobles** [ess-dive-community/essdive-uas#21]
* Documentation reference (URL): [UAS Data data product types and processing levels](https://github.com/ess-dive-community/essdive-uas/blob/main/5_DataProducts.md#Spectral-reflectance-json-files)

It could be nice to include a link to the CSV reporting format for data products that may be in CSV file formats (eg. Calibration panel reflectance reference lists CSV as an example file type), or point to the RF somewhere in the introductory paragraphs of the page. I'm not sure what these data products usually look like or what format they are typically in, so this may not be relevant or useful for data contributors.

**Comment by regnans** [comment]
I've added a link to the intro paragraph.
