### ISSUE TITLE
4a_SensorSpecs: Fnumber

### ISSUE THREAD

**Issue by emilyarobles** [ess-dive-community/essdive-uas#23]
* Documentation reference (URL):[https://github.com/ess-dive-community/essdive-uas/blob/main/4a_SensorSpecs.md#f-number]( https://github.com/ess-dive-community/essdive-uas/blob/main/4a_SensorSpecs.md#f-number)

The instructions list this as a numeric field, but it will be treated as text (F/#)

**Comment by regnans** [comment]
Should be text, I will change that.
